name: Deploy server

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy su server Hetzner via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 116.202.24.91
          username: root
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: bash /root/deploy_autotrack.sh
